const school = [
    {
    name:'University of Washington',
    sport1: 'swimming',
    sport2: 'football',
    sport3: 'baseball',
    region: 'Northwest',
    minAct: 21,
    schoolId: 1,
    },
    {
    name:'Minnesota State University',
    sport1: 'wrestling',
    sport2: 'football',
    sport3: 'softball',
    region: 'Midwest',
    minAct: 18,
    schoolId: 2,
    },
    {
    name:'Georgia Tech',
    sport1: 'football',
    sport2: 'swimming',
    sport3: 'baseball',
    region: 'Southeast',
    minAct: 20,
    schoolId: 3,
    },
    {
    name:'Central Arkansas',
    sport1: 'baseball',
    sport2: 'softball',
    sport3: 'vollyball',
    region: 'South',
    minAct: 19,
    schoolId: 4,
    },
];